version: "3.3"
services:
  web:
    container_name: nginx
    image: alqutami/rtmp-hls
    ports:
      - "8080:8080"
      - "1935:1935"

    volumes:
      - ./nginx:/usr/local/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - php-fpm
  php-fpm:
    container_name: php
    image: php:8-fpm
    volumes:
      - ./nginx:/usr/local/nginx
      
